project:
  type: website
  resources:
    - "documents/cv.pdf"

website:
  title: "David González Durán"
  navbar:
    left:
      - href: index.qmd
        text: About
      # - about.qmd

format:
  html:
    highlight-style: a11y
    theme:
      light: cosmo
      dark: [cosmo, style_dark.scss]
    css: styles.css
    toc: true



