project:
  type: website

website:
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About
      # - about.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    toc: true



